### ISSUE TITLE
NullReferenceException when clicking on Work Flow activity which has input variables

### ISSUE THREAD

**Issue by thijswm** [elsa-workflows/elsa-studio#487]
I get an null reference exception when I have created a work flow which is usable as an activity and has an input variable defined and I use that activity on another work flow. I am using elsa 3.3.5

Steps to reproduce:

- Create a work flow which is usable as an activity:

![Image](https://github.com/user-attachments/assets/cf55173b-8144-4ccb-9c66-f2d9de92f6bf)

- Define an input for this work flow

![Image](https://github.com/user-attachments/assets/c1acb405-f0e9-48e1-82a8-618113a02fa2)

- publish this work flow
- Create a new work flow where you add this activity

![Image](https://github.com/user-attachments/assets/ee3a6d26-fd77-4abf-bf77-a9980f096c4f)

- When you drag this activity on the designer, I directly get a null reference exception

![Image](https://github.com/user-attachments/assets/02e6af53-0cc1-42ba-8411-91124f01df42)

![Image](https://github.com/user-attachments/assets/177af749-cebd-4f82-aa13-9019701364c4)

Not sure how, but it seems the IsWrapped boolean should be false, but instead it is true

![Image](https://github.com/user-attachments/assets/aa9485fa-7d45-42b3-9543-a190c173e4d6)

**Comment by sfmskywalker** [comment]
I think this has been fixed after the 3.3.5 release. Would you be able to try it with the latest 3.4.0-preview.xxx packages?

**Comment by thijswm** [comment]
Thanks for the response.
I just tried it with _3.4.0-rc1_ and I get the same null reference exception

**Comment by sfmskywalker** [comment]
Many fixes have been made since 3.4.0-rc1 - can you try the latest 3.4.0-preview.xxx packages? I haven't been able to reproduce this with the rc/3.4.0 branch, but maybe my workflow is different. If you want to share an export of your workflows, I can try that too.

**Comment by MaxBrooks114** [comment]
@sfmskywalker   @thijswm  I have a PR for this https://github.com/elsa-workflows/elsa-studio/pull/498

**Comment by thijs-haarhuis-pdf** [comment]
> Many fixes have been made since 3.4.0-rc1 - can you try the latest 3.4.0-preview.xxx packages? I haven't been able to reproduce this with the rc/3.4.0 branch, but maybe my workflow is different. If you want to share an export of your workflows, I can try that too.

I just tried the 3.4.0 release and I still encounter the issue.
I have attached the "sub flow" I am using as activity.

[sub-flow.json](https://github.com/user-attachments/files/20457913/sub-flow.json)

When I place this activity now on the new flow I directly get a null reference eception

![Image](https://github.com/user-attachments/assets/5a10bbcb-b98b-4587-9e8c-8dec127654d1)

`[13:15:22 Warning] [Microsoft.AspNetCore.Components.Web.ErrorBoundary] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.GetSyntaxProvider(WrappedInput wrappedInput, InputDescriptor inputDescriptor)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.BuildInputEditorModels(JsonObject activity, ActivityDescriptor activityDescriptor, ICollection`1 inputDescriptors)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
[13:17:33 Warning] [Microsoft.AspNetCore.Components.Web.ErrorBoundary] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.GetSyntaxProvider(WrappedInput wrappedInput, InputDescriptor inputDescriptor)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.BuildInputEditorModels(JsonObject activity, ActivityDescriptor activityDescriptor, ICollection`1 inputDescriptors)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
[13:19:40 Warning] [Microsoft.AspNetCore.Components.Web.ErrorBoundary] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.GetSyntaxProvider(WrappedInput wrappedInput, InputDescriptor inputDescriptor)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.BuildInputEditorModels(JsonObject activity, ActivityDescriptor activityDescriptor, ICollection`1 inputDescriptors)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
[13:20:29 Warning] [Microsoft.AspNetCore.Components.Web.ErrorBoundary] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.GetSyntaxProvider(WrappedInput wrappedInput, InputDescriptor inputDescriptor)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.BuildInputEditorModels(JsonObject activity, ActivityDescriptor activityDescriptor, ICollection`1 inputDescriptors)
   at Elsa.Studio.Workflows.Components.WorkflowDefinitionEditor.Components.ActivityProperties.Tabs.InputsTab.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
`

**Comment by thijswm** [comment]
I just tried it with the 3.4.0 release and I still encounter the issue.
[sub-flow.json](https://github.com/user-attachments/files/20458090/sub-flow.json)
I have attached my "sub flow" work flow as activity
When I create a new work flow and place this activity on it, I directly get an exception.

![Image](https://github.com/user-attachments/assets/4f76cd68-0c43-4092-9a93-09cee093443b)

**Comment by KnibbsyMan** [comment]
Hi @thijswm,

I have just followed your steps to reproduce this in the develop/3.6.0 branch an I get no errors in doing so. I will close this issue for now but should you still be having problems let us know.
